image: 836782323787.dkr.ecr.us-east-1.amazonaws.com/android:android-ndk-r17c-sdk-28

variables:
  ANDROID_COMPILE_SDK:  "28"
  ANDROID_BUILD_TOOLS:  "28.0.2"
  ANDROID_SDK_TOOLS:    "6200805"
  ANDROID_NDK:          "android-ndk-r14b"

before_script:
  - chmod +x ./gradlew
  - echo "sdk.dir=${ANDROID_HOME}" >> local.properties
  - mkdir ~/.gradle
  - echo "VOXEET_MAVEN_PUBLISHED_GROUPID=com.voxeet.sdk" >  ~/.gradle/gradle.properties
  - echo "nexusUsername=${MAVEN_NEXUS_REPOSITORY_USER}" >> ~/.gradle/gradle.properties
  - echo "nexusPassword=${MAVEN_NEXUS_REPOSITORY_PASSWORD}" >> ~/.gradle/gradle.properties

stages:
  - deploy

snapshot_upload:
  stage: deploy
  script:
    - wget --quiet --output-document=android-ndk_compat.zip https://dl.google.com/android/repository/${ANDROID_NDK}-linux-x86_64.zip
    - unzip android-ndk_compat.zip
    - echo "ndk.dir=$PWD/${ANDROID_NDK}" > local.properties
    - ./gradlew :cleanAll
    - mkdir -p repository/com/voxeet/sdk
    - cp -r ~/.m2/repository/* repository/
    - ./gradlew -PINTERNAL_RELEASE="${MAVEN_NEXUS_REPOSITORY_URL}" -PCICD_BUILD_ID="SNAPSHOT" :uploadAll
  artifacts:
    paths:
      - ./repository
